"""mengubah tipe data pada table agent

Revision ID: a6fd29eddb3b
Revises: 6580201fcd88
Create Date: 2025-09-01 20:03:07.922613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6fd29eddb3b'
down_revision: Union[str, Sequence[str], None] = '6580201fcd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('plan', mysql.ENUM('free', 'normal', 'pro'), server_default=sa.text("'free'"), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('job_role', mysql.ENUM('AI engineer', 'sales', 'other'), server_default=sa.text("'other'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'non-active'), server_default=sa.text("'active'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
