"""Menambahkan kolom model di table agent

Revision ID: ff9a42160ba6
Revises: 626ba1dbc512
Create Date: 2025-09-01 16:15:31.185829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9a42160ba6'
down_revision: Union[str, Sequence[str], None] = '626ba1dbc512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
